name: 'MSBuild and Deploy'
description: 'Build and deploy'
inputs:
  project:
    description: 'The path to the csproj or sln file.'
    required: true
  password:
    description: 'The profile password'
    required: true
  publish-profile:
    description: 'The profile to use'
    required: false
    default: 'Default'
  configuration:
    description: 'Typically Release | Debug'
    required: false
    default: 'Release'
runs:
  using: 'node12'
  main: 'index.js'
